In [2]:
%pip install pytest

Requirement already satisfied: pytest in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (9.0.2)
Requirement already satisfied: colorama>=0.4 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from pytest) (0.4.6)
Requirement already satisfied: iniconfig>=1.0.1 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from pytest) (2.3.0)
Requirement already satisfied: packaging>=22 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from pytest) (25.0)
Requirement already satisfied: pluggy<2,>=1.5 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from pytest) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from pytest) (2.19.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
reference_data = [
  {
    "question": "What is the Privacy Policy?", 
    "ground_truth": "This Privacy Policy explains how Yellow Sapphire Consulting, collects, uses, and protects your personal information when you use the SpeakEQ mobile app.We comply with privacy laws including GDPR (for European users) and CCPA (for California users).", #Expected llm generated answer
    "context": "This Privacy Policy explains how Yellow Sapphire Consulting, collects, uses, and protects your personal information when you use the SpeakEQ mobile app.We comply with privacy laws including GDPR (for European users) and CCPA (for California users)." #Expected retrieved context
  }
]

# reference_data = [
#   {
#     "question": "What is the Privacy Policy?", 
#     "ground_truth": "This Privacy Policy explains how Yellow Sapphire Consulting, collects, uses, and protects your personal information when you use the SpeakEQ mobile app.We comply with privacy laws including GDPR (for European users) and CCPA (for California users)." #Expected llm generated answer
#     "context": "This Privacy Policy explains how Yellow Sapphire Consulting, collects, uses, and protects your personal information when you use the SpeakEQ mobile app.We comply with privacy laws including GDPR (for European users) and CCPA (for California users)." #Expected retrieved context
#   }
# ]
question = reference_data[0]['question']
ground_truth = reference_data[0]['ground_truth']
context = reference_data[0]['context']
print (f"question: {question}")
print (f"ground_truth: {ground_truth}")
print (f"context: {context}")

question: What is the Privacy Policy?
ground_truth: This Privacy Policy explains how Yellow Sapphire Consulting, collects, uses, and protects your personal information when you use the SpeakEQ mobile app.We comply with privacy laws including GDPR (for European users) and CCPA (for California users).
context: This Privacy Policy explains how Yellow Sapphire Consulting, collects, uses, and protects your personal information when you use the SpeakEQ mobile app.We comply with privacy laws including GDPR (for European users) and CCPA (for California users).

In [4]:
# Retrieve context from Milvus DB

from milvus_chatbot_with_rag import retrieve_similiar_contexts, generate_answer

def perform_retrieval(question):

    retrieved_context = retrieve_similiar_contexts(question, "policy_docs_collection", 1)[0]['content']
    print (f"perform_retrieval.retrieved_context: {retrieved_context}")
    return retrieved_context

# Generate answer using LLM

question = reference_data[0]['question']
context = perform_retrieval(question)
answer = generate_answer(question, context)
answer

Connected to Milvus on Zilliz Cloud
perform_retrieval.retrieved_context: Privacy Policy On the SpeakEQ app, we respect your privacy. This Privacy Policy explains how Yellow Sapphire Consulting, LLC DBA SpeakEQ ("we," "us," or "our") collects, uses, and protects your personal information when you use the SpeakEQ mobile app. We comply with privacy laws including GDPR (for European users) and CCPA (for California users).

'The Privacy Policy states that the SpeakEQ app respects your privacy. It explains how Yellow Sapphire Consulting, LLC (SpeakEQ, “we,” “us,” or “our”) collects, uses, and protects your personal information when you use the SpeakEQ mobile app. It also notes that we comply with privacy laws including GDPR (for European users) and CCPA (for California users).'

In [5]:
%pip install ragas datasets

Requirement already satisfied: ragas in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (0.4.3)
Requirement already satisfied: datasets in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (4.5.0)
Requirement already satisfied: numpy<3.0.0,>=1.21.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (2.3.0)
Requirement already satisfied: tiktoken in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (0.12.0)
Requirement already satisfied: pydantic>=2.0.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (2.12.5)
Requirement already satisfied: nest-asyncio in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (1.6.0)
Requirement already satisfied: appdirs in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (1.4.4)
Requirement already satisfied: diskcache>=5.6.3 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (5.6.3)
Requirement already satisfied: typer in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (0.21.1)
Requirement already satisfied: rich in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (14.3.2)
Requirement already satisfied: openai>=1.0.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (2.15.0)
Requirement already satisfied: tqdm in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (4.67.1)
Requirement already satisfied: instructor in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (1.14.5)
Requirement already satisfied: pillow>=10.4.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (12.1.0)
Requirement already satisfied: networkx in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (3.6.1)
Requirement already satisfied: scikit-network in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (0.33.5)
Requirement already satisfied: langchain in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (1.2.7)
Requirement already satisfied: langchain-core in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (1.2.7)
Requirement already satisfied: langchain-community in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (0.4.1)
Requirement already satisfied: langchain_openai in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from ragas) (1.1.7)
Requirement already satisfied: filelock in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from datasets) (3.20.3)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from datasets) (23.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: requests>=2.32.2 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from datasets) (0.70.18)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2025.10.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from datasets) (0.36.0)
Requirement already satisfied: packaging in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from openai>=1.0.0->ragas) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from openai>=1.0.0->ragas) (0.11.1)
Requirement already satisfied: sniffio in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from openai>=1.0.0->ragas) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from pydantic>=2.0.0->ragas) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from pydantic>=2.0.0->ragas) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from pydantic>=2.0.0->ragas) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: colorama in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from tqdm->ragas) (0.4.6)
Requirement already satisfied: docstring-parser<1.0,>=0.16 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from instructor->ragas) (0.17.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.4 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from instructor->ragas) (3.1.6)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from instructor->ragas) (9.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from jinja2<4.0.0,>=3.1.4->instructor->ragas) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from rich->ragas) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from rich->ragas) (2.19.2)
Requirement already satisfied: click>=8.0.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from typer->ragas) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from typer->ragas) (1.5.4)
Requirement already satisfied: mdurl~=0.1 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from markdown-it-py>=2.2.0->rich->ragas) (0.1.2)
Requirement already satisfied: langgraph<1.1.0,>=1.0.7 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langchain->ragas) (1.0.7)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langchain-core->ragas) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langchain-core->ragas) (0.6.7)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langchain-core->ragas) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core->ragas) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langgraph<1.1.0,>=1.0.7->langchain->ragas) (4.0.0)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.7 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langgraph<1.1.0,>=1.0.7->langchain->ragas) (1.0.7)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langgraph<1.1.0,>=1.0.7->langchain->ragas) (0.3.3)
Requirement already satisfied: ormsgpack>=1.12.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.7->langchain->ragas) (1.12.2)
Requirement already satisfied: orjson>=3.10.1 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.7->langchain->ragas) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core->ragas) (0.25.0)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langchain-community->ragas) (1.0.1)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langchain-community->ragas) (2.0.46)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langchain-community->ragas) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langchain-community->ragas) (2.12.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langchain-community->ragas) (0.4.3)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community->ragas) (1.1.0)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community->ragas) (1.2.1)
Requirement already satisfied: greenlet>=1 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community->ragas) (3.3.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community->ragas) (1.1.0)
Requirement already satisfied: regex>=2022.1.18 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from tiktoken->ragas) (2026.1.15)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: scipy>=1.7.3 in c:\users\nirma\training\genai_projects\.venv\lib\site-packages (from scikit-network->ragas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
from datasets import Dataset
from ragas import evaluate
from ragas.metrics import faithfulness, answer_correctness

from dotenv import load_dotenv
from openai import OpenAI
import os

# --- Load API Key ---
load_dotenv(override=True, dotenv_path="../.env")
my_api_key = os.getenv("OPENAI_API_KEY")


client = OpenAI(api_key=my_api_key)

# Question User asked
question = reference_data[0]['question']

# Reference context (should be a string)
reference_context = reference_data[0]['context']

# ground truth answer
ground_truth = reference_data[0]['ground_truth']

# Retrieved context (a string from perform_retrieval)
retrieved_context = [perform_retrieval(question)]
llm_answer = generate_answer(question, retrieved_context[0])

# Build dataset properly
dataset_dict = {
    "question": [question],
    "contexts": [retrieved_context],    # list of strings INSIDE another list
    "ground_truth": [ground_truth],   # single string/ reference answer
    "answer": [llm_answer]
}

print(f"dataset_dict: {dataset_dict}")

ragas_dataset = Dataset.from_dict(dataset_dict)

C:\Users\nirma\AppData\Local\Temp\ipykernel_53488\3667568502.py:3: DeprecationWarning: Importing faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import faithfulness
  from ragas.metrics import faithfulness, answer_correctness
C:\Users\nirma\AppData\Local\Temp\ipykernel_53488\3667568502.py:3: DeprecationWarning: Importing answer_correctness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_correctness
  from ragas.metrics import faithfulness, answer_correctness

Connected to Milvus on Zilliz Cloud
perform_retrieval.retrieved_context: Privacy Policy On the SpeakEQ app, we respect your privacy. This Privacy Policy explains how Yellow Sapphire Consulting, LLC DBA SpeakEQ ("we," "us," or "our") collects, uses, and protects your personal information when you use the SpeakEQ mobile app. We comply with privacy laws including GDPR (for European users) and CCPA (for California users).
dataset_dict: {'question': ['What is the Privacy Policy?'], 'contexts': [['Privacy Policy On the SpeakEQ app, we respect your privacy. This Privacy Policy explains how Yellow Sapphire Consulting, LLC DBA SpeakEQ ("we," "us," or "our") collects, uses, and protects your personal information when you use the SpeakEQ mobile app. We comply with privacy laws including GDPR (for European users) and CCPA (for California users).']], 'ground_truth': ['This Privacy Policy explains how Yellow Sapphire Consulting, collects, uses, and protects your personal information when you use the SpeakEQ mobile app.We comply with privacy laws including GDPR (for European users) and CCPA (for California users).'], 'answer': ['The Privacy Policy is a document from Yellow Sapphire Consulting, LLC DBA SpeakEQ that explains how they collect, use, and protect your personal information when you use the SpeakEQ mobile app. It also notes that they comply with privacy laws, including GDPR for European users and CCPA for California users.']}

In [7]:
from ragas.llms.base import llm_factory
from ragas import evaluate
from ragas.metrics import answer_correctness

results = evaluate(
    dataset=ragas_dataset,
    metrics=[faithfulness, answer_correctness]  
)


print("LLM Generation Evaluation Results:")
results.to_pandas()

C:\Users\nirma\AppData\Local\Temp\ipykernel_53488\1314932040.py:3: DeprecationWarning: Importing answer_correctness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_correctness
  from ragas.metrics import answer_correctness

Evaluating:   0%|          | 0/2 [00:00<?, ?it/s]

Exception raised in Job[1]: TypeError(Cannot use aembed_text() with a synchronous client. Use embed_text() instead.)

LLM Generation Evaluation Results:

,user_input,retrieved_contexts,response,reference,faithfulness,answer_correctness
0,What is the Privacy Policy?,"[Privacy Policy On the SpeakEQ app, we respect...",The Privacy Policy is a document from Yellow S...,This Privacy Policy explains how Yellow Sapphi...,1.0,NaN

In [8]:
from ragas.llms.base import llm_factory
from ragas import evaluate
from ragas.metrics import answer_correctness

# Create the modern LLM wrapper
client = OpenAI()
llm = llm_factory("gpt-4o-mini", client=client)

# Run evaluation
results = evaluate(
    dataset=ragas_dataset,
    metrics=[answer_correctness],
    llm=llm
)

print("LLM Generation Evaluation Results:")
results.to_pandas()

C:\Users\nirma\AppData\Local\Temp\ipykernel_53488\1016587815.py:3: DeprecationWarning: Importing answer_correctness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import answer_correctness
  from ragas.metrics import answer_correctness

Evaluating:   0%|          | 0/1 [00:00<?, ?it/s]

Exception raised in Job[0]: TypeError(Cannot use aembed_text() with a synchronous client. Use embed_text() instead.)

LLM Generation Evaluation Results:

,user_input,retrieved_contexts,response,reference,answer_correctness
0,What is the Privacy Policy?,"[Privacy Policy On the SpeakEQ app, we respect...",The Privacy Policy is a document from Yellow S...,This Privacy Policy explains how Yellow Sapphi...,NaN